name: event_hub
description: Smart Event Management Platform (EventHub + Smart Events + Day 5 Reviews/Favorites merged)

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.1.0
  cupertino_icons: ^1.0.6
  cached_network_image: ^3.3.1
  url_launcher: ^6.2.5
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/events.json
